"""empty message

Revision ID: 142451052730
Revises: e7e6cd0de78d
Create Date: 2021-10-19 14:40:31.509886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '142451052730'
down_revision = 'e7e6cd0de78d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_artist_artistname', table_name='artist')
    op.create_index(op.f('ix_artist_artistname'), 'artist', ['artistname'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artist_artistname'), table_name='artist')
    op.create_index('ix_artist_artistname', 'artist', ['artistname'], unique=False)
    # ### end Alembic commands ###
