"""empty message

Revision ID: 4e1537b0d084
Revises: d89039bda62b
Create Date: 2021-10-19 15:36:08.747344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e1537b0d084'
down_revision = 'd89039bda62b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_event_date', table_name='event')
    op.drop_index('ix_event_eventname', table_name='event')
    op.drop_table('event')
    op.drop_index('ix_venue_eventID', table_name='venue')
    op.drop_index('ix_venue_venuename', table_name='venue')
    op.drop_table('venue')
    op.drop_index('ix_artist_artistname', table_name='artist')
    op.drop_index('ix_artist_description', table_name='artist')
    op.drop_index('ix_artist_hometown', table_name='artist')
    op.drop_table('artist')
    op.drop_index('ix_artist_to_event_artistID', table_name='artist_to_event')
    op.drop_index('ix_artist_to_event_eventID', table_name='artist_to_event')
    op.drop_table('artist_to_event')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist_to_event',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('artistID', sa.INTEGER(), nullable=True),
    sa.Column('eventID', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_artist_to_event_eventID', 'artist_to_event', ['eventID'], unique=False)
    op.create_index('ix_artist_to_event_artistID', 'artist_to_event', ['artistID'], unique=False)
    op.create_table('artist',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('artistname', sa.VARCHAR(length=64), nullable=True),
    sa.Column('description', sa.VARCHAR(length=120), nullable=True),
    sa.Column('hometown', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_artist_hometown', 'artist', ['hometown'], unique=False)
    op.create_index('ix_artist_description', 'artist', ['description'], unique=False)
    op.create_index('ix_artist_artistname', 'artist', ['artistname'], unique=False)
    op.create_table('venue',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('venuename', sa.VARCHAR(length=64), nullable=True),
    sa.Column('eventID', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_venue_venuename', 'venue', ['venuename'], unique=False)
    op.create_index('ix_venue_eventID', 'venue', ['eventID'], unique=False)
    op.create_table('event',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('eventname', sa.VARCHAR(length=64), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_event_eventname', 'event', ['eventname'], unique=False)
    op.create_index('ix_event_date', 'event', ['date'], unique=False)
    # ### end Alembic commands ###
