"""empty message

Revision ID: d89039bda62b
Revises: 142451052730
Create Date: 2021-10-19 14:52:26.575537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd89039bda62b'
down_revision = '142451052730'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('hometown', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_artist_hometown'), 'artist', ['hometown'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artist_hometown'), table_name='artist')
    op.drop_column('artist', 'hometown')
    # ### end Alembic commands ###
