"""empty message

Revision ID: e7e6cd0de78d
Revises: 
Create Date: 2021-10-19 14:29:26.703812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7e6cd0de78d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artistname', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artist_artistname'), 'artist', ['artistname'], unique=True)
    op.create_index(op.f('ix_artist_description'), 'artist', ['description'], unique=False)
    op.create_table('artist_to_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artistID', sa.Integer(), nullable=True),
    sa.Column('eventID', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artist_to_event_artistID'), 'artist_to_event', ['artistID'], unique=False)
    op.create_index(op.f('ix_artist_to_event_eventID'), 'artist_to_event', ['eventID'], unique=False)
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eventname', sa.String(length=64), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_date'), 'event', ['date'], unique=False)
    op.create_index(op.f('ix_event_eventname'), 'event', ['eventname'], unique=False)
    op.create_table('venue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venuename', sa.String(length=64), nullable=True),
    sa.Column('eventID', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venue_eventID'), 'venue', ['eventID'], unique=False)
    op.create_index(op.f('ix_venue_venuename'), 'venue', ['venuename'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_venue_venuename'), table_name='venue')
    op.drop_index(op.f('ix_venue_eventID'), table_name='venue')
    op.drop_table('venue')
    op.drop_index(op.f('ix_event_eventname'), table_name='event')
    op.drop_index(op.f('ix_event_date'), table_name='event')
    op.drop_table('event')
    op.drop_index(op.f('ix_artist_to_event_eventID'), table_name='artist_to_event')
    op.drop_index(op.f('ix_artist_to_event_artistID'), table_name='artist_to_event')
    op.drop_table('artist_to_event')
    op.drop_index(op.f('ix_artist_description'), table_name='artist')
    op.drop_index(op.f('ix_artist_artistname'), table_name='artist')
    op.drop_table('artist')
    # ### end Alembic commands ###
